directories:
  output: dist
  buildResources: build
win:
  target: portable
  icon: srti_modules/srti_logo/srti_logo_dark_512_icon.ico
  extraResources:
    - ./extraResources/**
electronVersion: 6.0.8
